(ns agent.builtin-extensions
  "Every builtin extension, imported statically.

   Generated by scripts/gen-builtin-extensions.mjs — do not edit by hand.
   Run 'bun run gen:builtins' after adding or removing an extension;
   test/builtin_extensions.test.cljs fails when this file is stale.

   Why static: the loader used to find these by scanning the directory they
   compile into, which cannot work inside a single-file binary — the scan path
   resolves into the bundle, finds nothing, and an empty scan is not an error. A
   bundled nyma therefore shipped with 2 of 40 extensions and 3 of 20 providers.
   Static requires put them in the bundle graph, and the manifests are inlined
   because extension.json is a file read that has nowhere to read from either.

   User extensions are unaffected: they are still discovered by scanning
   ~/.nyma/extensions and .nyma/extensions, which are real directories on the
   machine running nyma."
  (:require [agent.extensions.add-dir.index :as ext-add-dir]
            [agent.extensions.advisor.index :as ext-advisor]
            [agent.extensions.agent-runner-claude-sdk.index :as ext-agent-runner-claude-sdk]
            [agent.extensions.agent-shell.index :as ext-agent-shell]
            [agent.extensions.agent-state.index :as ext-agent-state]
            [agent.extensions.ast-tools.index :as ext-ast-tools]
            [agent.extensions.bash-suite.index :as ext-bash-suite]
            [agent.extensions.budget.index :as ext-budget]
            [agent.extensions.checkpoints.index :as ext-checkpoints]
            [agent.extensions.claude-hook-bridge.index :as ext-claude-hook-bridge]
            [agent.extensions.custom-provider-claude-native.index :as ext-custom-provider-claude-native]
            [agent.extensions.custom-provider-deepseek.index :as ext-custom-provider-deepseek]
            [agent.extensions.custom-provider-groq.index :as ext-custom-provider-groq]
            [agent.extensions.custom-provider-kimi.index :as ext-custom-provider-kimi]
            [agent.extensions.custom-provider-local.index :as ext-custom-provider-local]
            [agent.extensions.custom-provider-minimax.index :as ext-custom-provider-minimax]
            [agent.extensions.custom-provider-opencode-zen.index :as ext-custom-provider-opencode-zen]
            [agent.extensions.custom-provider-openrouter.index :as ext-custom-provider-openrouter]
            [agent.extensions.custom-provider-qwen-cli.index :as ext-custom-provider-qwen-cli]
            [agent.extensions.custom-provider-relay.index :as ext-custom-provider-relay]
            [agent.extensions.desktop-notify.index :as ext-desktop-notify]
            [agent.extensions.handoff.index :as ext-handoff]
            [agent.extensions.headroom.index :as ext-headroom]
            [agent.extensions.lsp-suite.index :as ext-lsp-suite]
            [agent.extensions.mcp-client.index :as ext-mcp-client]
            [agent.extensions.memory.index :as ext-memory]
            [agent.extensions.model-roles.index :as ext-model-roles]
            [agent.extensions.openwiki.index :as ext-openwiki]
            [agent.extensions.prompt-history.index :as ext-prompt-history]
            [agent.extensions.questionnaire.index :as ext-questionnaire]
            [agent.extensions.refine.index :as ext-refine]
            [agent.extensions.small-model.index :as ext-small-model]
            [agent.extensions.spec-driven.index :as ext-spec-driven]
            [agent.extensions.stats-dashboard.index :as ext-stats-dashboard]
            [agent.extensions.subagent.index :as ext-subagent]
            [agent.extensions.thinking-renderer.index :as ext-thinking-renderer]
            [agent.extensions.todos.index :as ext-todos]
            [agent.extensions.token-suite.index :as ext-token-suite]
            [agent.extensions.verify-gate.index :as ext-verify-gate]
            [agent.extensions.workspace-config.index :as ext-workspace-config]))

(def registry
  "[{:namespace :module :manifest}] — fed to extension-loader/discover-and-load
   alongside the user-directory scan, and run through the same topological sort,
   capability parsing and activation as anything it finds on disk."
  [
   {:namespace "add-dir"
    :module    ext-add-dir
    :manifest  #js {"namespace" "add-dir" "capabilities" #js ["events" "commands"] "dependsOn" #js []}}
   {:namespace "advisor"
    :module    ext-advisor
    :manifest  #js {"namespace" "advisor" "capabilities" #js ["tools" "commands" "model" "state"] "dependsOn" #js []}}
   {:namespace "agent-runner-claude-sdk"
    :module    ext-agent-runner-claude-sdk
    :manifest  #js {"namespace" "agent-runner-claude-sdk" "capabilities" #js ["events"] "dependsOn" #js ["agent-shell"] "dependencies" #js {"@anthropic-ai/claude-agent-sdk" "*"}}}
   {:namespace "agent-shell"
    :module    ext-agent-shell
    :manifest  #js {"namespace" "agent-shell" "capabilities" #js ["spawn" "commands" "events" "ui" "messages" "flags" "state"] "dependsOn" #js ["model-roles"]}}
   {:namespace "agent-state"
    :module    ext-agent-state
    :manifest  #js {"namespace" "agent-state" "capabilities" #js ["events" "spawn"] "dependsOn" #js []}}
   {:namespace "ast-tools"
    :module    ext-ast-tools
    :manifest  #js {"namespace" "ast-tools" "capabilities" #js ["tools" "exec"]}}
   {:namespace "bash-suite"
    :module    ext-bash-suite
    :manifest  #js {"namespace" "bash-suite" "capabilities" #js ["events" "tools" "middleware" "commands"] "dependsOn" #js [] "dependencies" #js {"shell-quote" "^1.9.0"}}}
   {:namespace "budget"
    :module    ext-budget
    :manifest  #js {"namespace" "budget" "capabilities" #js ["events"] "dependsOn" #js []}}
   {:namespace "checkpoints"
    :module    ext-checkpoints
    :manifest  #js {"namespace" "checkpoints" "capabilities" #js ["events" "commands"] "dependsOn" #js []}}
   {:namespace "claude-hook-bridge"
    :module    ext-claude-hook-bridge
    :manifest  #js {"namespace" "claude-hook-bridge" "capabilities" #js ["events" "state" "messages" "ui"] "dependsOn" #js ["agent-shell" "token-suite"]}}
   {:namespace "custom-provider-claude-native"
    :module    ext-custom-provider-claude-native
    :manifest  #js {"namespace" "custom-provider-claude-native" "capabilities" #js ["providers"] "dependsOn" #js [] "dependencies" #js {}}}
   {:namespace "custom-provider-deepseek"
    :module    ext-custom-provider-deepseek
    :manifest  #js {"namespace" "custom-provider-deepseek" "capabilities" #js ["providers"] "dependsOn" #js [] "dependencies" #js {}}}
   {:namespace "custom-provider-groq"
    :module    ext-custom-provider-groq
    :manifest  #js {"namespace" "custom-provider-groq" "capabilities" #js ["providers" "model"] "dependsOn" #js [] "dependencies" #js {}}}
   {:namespace "custom-provider-kimi"
    :module    ext-custom-provider-kimi
    :manifest  #js {"namespace" "custom-provider-kimi" "capabilities" #js ["providers" "model"] "dependsOn" #js [] "dependencies" #js {}}}
   {:namespace "local"
    :module    ext-custom-provider-local
    :manifest  #js {"namespace" "local" "capabilities" #js ["providers"] "dependsOn" #js []}}
   {:namespace "custom-provider-minimax"
    :module    ext-custom-provider-minimax
    :manifest  #js {"namespace" "custom-provider-minimax" "capabilities" #js ["providers"] "dependsOn" #js [] "dependencies" #js {}}}
   {:namespace "custom-provider-opencode-zen"
    :module    ext-custom-provider-opencode-zen
    :manifest  #js {"namespace" "custom-provider-opencode-zen" "capabilities" #js ["providers"] "dependsOn" #js [] "dependencies" #js {}}}
   {:namespace "custom-provider-openrouter"
    :module    ext-custom-provider-openrouter
    :manifest  #js {"namespace" "custom-provider-openrouter" "capabilities" #js ["providers" "model"] "dependsOn" #js [] "dependencies" #js {}}}
   {:namespace "custom-provider-qwen-cli"
    :module    ext-custom-provider-qwen-cli
    :manifest  #js {"namespace" "custom-provider-qwen-cli" "capabilities" #js ["providers"] "dependsOn" #js [] "dependencies" #js {}}}
   {:namespace "custom-provider-relay"
    :module    ext-custom-provider-relay
    :manifest  #js {"namespace" "custom-provider-relay" "capabilities" #js ["providers" "model"] "dependsOn" #js [] "dependencies" #js {}}}
   {:namespace "desktop-notify"
    :module    ext-desktop-notify
    :manifest  #js {"namespace" "desktop-notify" "capabilities" #js ["events" "flags"] "dependsOn" #js []}}
   {:namespace "handoff"
    :module    ext-handoff
    :manifest  #js {"namespace" "handoff" "capabilities" #js ["events" "commands" "state"] "dependsOn" #js []}}
   {:namespace "headroom"
    :module    ext-headroom
    :manifest  #js {"namespace" "headroom" "capabilities" #js ["events" "commands"] "dependsOn" #js [] "dependencies" #js {"headroom-ai" "^0.22.4"}}}
   {:namespace "lsp-suite"
    :module    ext-lsp-suite
    :manifest  #js {"namespace" "lsp-suite" "capabilities" #js ["tools" "events"] "dependsOn" #js [] "dependencies" #js {"vscode-jsonrpc" "^9.0.0"}}}
   {:namespace "mcp-client"
    :module    ext-mcp-client
    :manifest  #js {"namespace" "mcp-client" "capabilities" #js ["events" "tools" "tools-override" "commands" "ui"] "dependsOn" #js ["agent-shell"]}}
   {:namespace "memory"
    :module    ext-memory
    :manifest  #js {"namespace" "memory" "capabilities" #js ["events" "tools"] "dependsOn" #js []}}
   {:namespace "model-roles"
    :module    ext-model-roles
    :manifest  #js {"namespace" "model-roles" "capabilities" #js ["events" "commands" "model" "state" "ui" "messages" "shortcuts"] "dependsOn" #js []}}
   {:namespace "openwiki"
    :module    ext-openwiki
    :manifest  #js {"namespace" "openwiki" "capabilities" #js ["events" "commands" "tools" "flags" "ui"] "dependsOn" #js []}}
   {:namespace "prompt-history"
    :module    ext-prompt-history
    :manifest  #js {"namespace" "prompt-history" "capabilities" #js ["commands" "events" "shortcuts" "ui"] "dependsOn" #js []}}
   {:namespace "questionnaire"
    :module    ext-questionnaire
    :manifest  #js {"namespace" "questionnaire" "capabilities" #js ["tools" "ui"] "dependsOn" #js []}}
   {:namespace "refine"
    :module    ext-refine
    :manifest  #js {"namespace" "refine" "capabilities" #js ["commands" "ui"] "dependsOn" #js [] "dependencies" #js {}}}
   {:namespace "small-model"
    :module    ext-small-model
    :manifest  #js {"namespace" "small-model" "capabilities" #js ["events" "model" "middleware" "tools" "tools-override" "flags" "state" "messages"] "dependsOn" #js ["advisor"]}}
   {:namespace "spec-driven"
    :module    ext-spec-driven
    :manifest  #js {"namespace" "spec-driven" "capabilities" #js ["events" "commands" "state" "ui" "messages"] "dependsOn" #js []}}
   {:namespace "stats-dashboard"
    :module    ext-stats-dashboard
    :manifest  #js {"namespace" "stats-dashboard" "capabilities" #js ["commands" "events" "state" "ui"] "dependsOn" #js []}}
   {:namespace "subagent"
    :module    ext-subagent
    :manifest  #js {"namespace" "subagent" "capabilities" #js ["tools" "commands" "model" "ui" "messages"] "dependsOn" #js ["model-roles"]}}
   {:namespace "thinking-renderer"
    :module    ext-thinking-renderer
    :manifest  #js {"namespace" "thinking-renderer" "capabilities" #js ["events" "ui" "flags"] "dependsOn" #js []}}
   {:namespace "todos"
    :module    ext-todos
    :manifest  #js {"namespace" "todos" "capabilities" #js ["events" "tools" "ui" "state"] "dependsOn" #js []}}
   {:namespace "token-suite"
    :module    ext-token-suite
    :manifest  #js {"namespace" "token-suite" "capabilities" #js ["events" "context" "tools" "middleware" "commands" "ui"] "dependsOn" #js []}}
   {:namespace "verify-gate"
    :module    ext-verify-gate
    :manifest  #js {"namespace" "verify-gate" "capabilities" #js ["events" "messages"] "dependsOn" #js []}}
   {:namespace "workspace-config"
    :module    ext-workspace-config
    :manifest  #js {"namespace" "workspace-config" "capabilities" #js ["commands" "ui"] "dependsOn" #js []}}])
