(ns agent.version
  "The version, baked in at build time.

   Generated by scripts/gen-version.mjs from package.json — do not edit.
   Regenerated by 'bun run build', so it cannot drift from package.json.

   Why generated rather than read: a compiled binary has no package.json to
   read, and Bun does not autoload one into a standalone executable."
  )

(def version "0.11.0")
