#!/usr/bin/env bun
// Regenerates src/agent/version.cljs from package.json.
//
// A compiled nyma cannot read package.json: there are no files inside the
// binary, and `--compile-autoload-package-json` defaults to false anyway. So
// the version has to be baked in at build time.
//
// This runs as part of `bun run build`, which every `bundle:*` script calls
// first — so the constant cannot go stale and needs no drift test. Do not edit
// the generated file; bump the version in package.json.

import { readFileSync, writeFileSync } from "node:fs";

const OUT = "src/agent/version.cljs";

export function render(version) {
  return `(ns agent.version
  "The version, baked in at build time.

   Generated by scripts/gen-version.mjs from package.json — do not edit.
   Regenerated by 'bun run build', so it cannot drift from package.json.

   Why generated rather than read: a compiled binary has no package.json to
   read, and Bun does not autoload one into a standalone executable."
  )

(def version "${version}")
`;
}

if (import.meta.main) {
  const { version } = JSON.parse(readFileSync("package.json", "utf8"));
  writeFileSync(OUT, render(version));
  console.log(`${OUT} — ${version}`);
}
