(ns agent.dev.event-map
  "Generates docs/event-map.md: every core event with its emitters and its
   listeners, and every extension-API registry with its producers and consumers.

   Borrowed from deepseek-harness's generated `docs/event-producer-consumer.md`.
   Its discipline is not 'never ship an event with no listener' — it prints a
   bare `-` and moves on — it is that neither column is ever unknown. nyma had
   the emitter half as a failing lint and no view of the listener half, and the
   registry half lived in a roadmap table maintained by hand, which is how five
   registries with no consumer lived long enough to need their own commit.

   Report, don't fail: a zero-listener row is a fact on the page. The only
   failure is drift between the committed file and the source."
  (:require ["node:fs" :as fs]
            ["node:path" :as path]
            [clojure.string :as str]
            [agent.events :as events]
            [agent.loop :as agent-loop]))

(def ^:private src-root (path/resolve (js/process.cwd) "src"))

(defn- cljs-files [dir]
  (reduce
   (fn [acc e]
     (let [p (path/join dir (.-name e))]
       (cond
         (.isDirectory e)               (into acc (cljs-files p))
         (.endsWith (.-name e) ".cljs") (conj acc p)
         :else                          acc)))
   []
   (vec (fs/readdirSync dir #js {:withFileTypes true}))))

(defn- rel [p] (str "src/" (path/relative src-root p)))

(defn- names-matching
  "Event names in `source` matched by `re`, whose first group is the name."
  [re source]
  (set (map second (re-seq re (str source)))))

(def ^:private emit-re
  #"(?:emit|emit-async|emit-collect|emitGlobal|emit-fn|emit!)[^\n\"]{0,40}\"([a-zA-Z][a-zA-Z0-9_]*)\"")

(def ^:private listen-re
  #"(?:\.on|\(:on|:on\b)[^\n\"]{0,40}\"([a-zA-Z][a-zA-Z0-9_]*)\"")

(def ^:private register-re
  ;; Both call shapes: `(.registerX api …)` and the guarded
  ;; `(when-let [reg (.-registerX api)] (reg …))` that status segments use.
  #"\.-?(register[A-Z][a-zA-Z]*)\b")

(defn scan
  "Walk src once. Returns {:emitters {event #{file}} :listeners {event #{file}}
   :registry-calls {api-name #{file}}}."
  []
  (reduce
   (fn [acc f]
     (let [src (fs/readFileSync f "utf8")
           r   (rel f)
           add (fn [m k] (update m k (fnil conj #{}) r))]
       (-> acc
           (update :emitters  (fn [m] (reduce add m (names-matching emit-re src))))
           (update :listeners (fn [m] (reduce add m (names-matching listen-re src))))
           (update :registry-calls
                   (fn [m] (reduce add m (set (map second (re-seq register-re src)))))))))
   {:emitters {} :listeners {} :registry-calls {}}
   (cljs-files src-root)))

(def ^:private stream-mapped
  "Names emitted by mapping a stream chunk type through loop.cljs's
   `stream-event-types` — read from the map so this can never be a stale
   hand-written allow-list."
  (set (map str (vec (js/Object.values agent-loop/stream-event-types)))))

(defn- cell [files]
  (if (seq files) (str/join ", " (sort files)) "-"))

(defn- event-rows [scanned]
  (let [{:keys [emitters listeners]} scanned]
    (for [n (sort (map str (vec events/core-event-types)))]
      (let [emits (get emitters n)
            emits (if (contains? stream-mapped n)
                    (conj (or emits #{}) "src/agent/loop.cljs (stream-event-types)")
                    emits)]
        (str "| `" n "` | " (cell emits) " | " (cell (get listeners n)) " |")))))

(defn- pi-rows [scanned]
  (for [n (sort (map str (vec events/pi-compat-event-types)))]
    (str "| `" n "` | " (cell (get (:listeners scanned) n)) " |")))

(def ^:private non-producers
  "extensions.cljs DEFINES these APIs and extension_scope.cljs forwards them;
   this file only names them in prose. None is a call site."
  #{"src/agent/extensions.cljs" "src/agent/extension_scope.cljs"
    "src/agent/dev/event_map.cljs"})

(defn declared-registries
  "The `registerX` keys `extensions.cljs` actually defines. Rows come from HERE,
   not from the call sites, so an API that nothing calls still gets a row with a
   `-` — which is the whole point: a registry nobody fills is as interesting as
   one nobody reads."
  []
  (let [src (fs/readFileSync (path/join src-root "agent" "extensions.cljs") "utf8")]
    (set (map second (re-seq #":(register[A-Z][a-zA-Z]*)\s" src)))))

(defn- registry-rows [scanned]
  (let [calls (:registry-calls scanned)]
    (for [n (sort (declared-registries))]
      (str "| `" n "` | " (cell (remove non-producers (get calls n))) " |"))))

(defn render-event-map
  "The full document. Pure apart from reading src."
  []
  (let [scanned (scan)]
    (str/join
     "\n"
     (concat
      ["<!-- Generated by scripts/gen-event-map.mjs — do not edit by hand."
       "     Run `bun run gen:event-map` to regenerate. -->"
       ""
       "# Event and registry map"
       ""
       "Who produces each extension point, and who consumes it. A `-` is a fact, not"
       "a failure: an event with no listener is a hook nobody has taken up yet. What"
       "this file exists to prevent is the column being *unknown* — five registries"
       "with no consumer survived several releases because nothing showed the pair."
       ""
       "## Core events"
       ""
       "`test/event_emitter_lint.test.cljs` fails when the emitters column is empty."
       "The listeners column is reported only."
       ""
       "| Event | Emitted in | Listened in |"
       "| --- | --- | --- |"]
      (event-rows scanned)
      [""
       "## pi-compat events"
       ""
       "Declared for pi API parity; nyma itself never emits these. A listener here is"
       "waiting for something only a pi-style host produces."
       ""
       "| Event | Listened in |"
       "| --- | --- |"]
      (pi-rows scanned)
      [""
       "## Extension-API registries"
       ""
       "Producers of each `registerX` on the extension API. The consumer is the code"
       "that reads the registry back; a registry with producers and no reader is the"
       "shape that got `registerBlockRenderer`, `registerToolRenderer`,"
       "`registerCompletionProvider`, `registerMentionProvider` and"
       "`registerContextProvider` deleted on 2026-09-11."
       ""
       "| API | Called from |"
       "| --- | --- |"]
      (registry-rows scanned)
      [""]))))
